pipeline {
    agent any
    stages {
        stage('Clean Up') {
            steps {
                deleteDir()
            }
        }
        stage('Checkout SCM') {
            steps {
                checkout scm
                sh 'pwd' // to check the present working directory
            }
        }
        stage('Terraform Stage') {
            steps {
                dir('Day1') {
                    sh """
                        pwd // to check the current directory
                        terraform init
                        terraform plan
                        terraform apply --auto-approve
                    """
                }
            }    
        }
        stage('Input message') {
            steps {
                input message: 'Destroy Terraform Resources?' 
            }
        }
        stage('Search and Destroy') {
            steps {
                sh 'cd Day1; terraform destroy --auto-approve' // can also use dir()
            }
        }
    }
}